src/AvaloniaEdit/Editing/TextArea.cs
src/AvaloniaEdit/Rendering/TextView.cs
src/AvaloniaEdit/Text/TextLineImpl.cs
src/AvaloniaEdit/Utils/PixelSnapHelpers.cs

Generate visual lines sometimes was returning null and crashing, this cant happen anymore.
Arrange and measure now works correctly, fixes #23 
Mouse click scrolling and caret navigation now works as expected.
PixelSnap helpers are public for people creating their own background renderers.

Minor Fixes

---

src/AvaloniaEdit/Document/TextDocument.cs

Not neccesarily the ui thread.

verify access checks against thread textdocument is created on.

---

src/AvaloniaEdit/Editing/SelectionMouseHandler.cs

Selection handler marked all mouse button events as handled even if it only handled left mouse button.

Fixed selection handler eating all mouse button events.

---

src/AvaloniaEdit/Folding/FoldingMargin.cs

Before:
After:
Notice the changes in the folding margin.

Fix rendering of FoldingMarginMarkers

---

src/AvaloniaEdit/Rendering/FormattedTextElement.cs
src/AvaloniaEdit/Rendering/InlineObjectRun.cs
src/AvaloniaEdit/Rendering/SingleCharacterElementGenerator.cs
src/AvaloniaEdit/Rendering/TextView.cs
src/AvaloniaEdit/Text/TextEmbeddedObject.cs
src/AvaloniaEdit/Text/TextLineRun.cs

This fixes:
* Pointer events not reaching TextView
* Double click on folding element opens fold.
* Rendering bugs with FoldingLineElement
Before:
After:

Folding element fixes

---

src/AvaloniaEdit.Demo/MainWindow.xaml
src/AvaloniaEdit.Demo/MainWindow.xaml.cs
src/AvaloniaEdit/Rendering/InlineObjectRun.cs
src/AvaloniaEdit/Rendering/TextView.cs
src/AvaloniaEdit/Text/TextLineImpl.cs
src/AvaloniaEdit/Text/TextLineRun.cs

Fixes:
- Inline object does not show up
- The line with Inline objects may collapse 
Known issues:
- Cannot scroll down if the height of the inline object is large ( because TextView's scroll size depends on the number of lines)

Fix inline objects

---

src/AvaloniaEdit/Rendering/VisualLineLinkText.cs

OpenUri as a routed event. It should be handled by application (Open browser or navigate to another page in app). 
Similar to
https://docs.microsoft.com/en-us/dotnet/api/system.windows.documents.hyperlink.requestnavigate?view=netframework-4.7.2

Open uri routed event

---

src/AvaloniaEdit/AvaloniaEditCommands.cs
src/AvaloniaEdit/Editing/CaretNavigationCommandHandler.cs

* Replace shortcut for mac is set to CMD + ALT + F because CMD + H is used for "hide window" system command
Fixes: #78

Fix editor shortcuts on mac replacing ctrl with cmd

---

src/AvaloniaEdit/AvaloniaEditCommands.cs

This fixes the Mac shortcuts that the previous committed fix didn't handle.
https://github.com/AvaloniaUI/AvaloniaEdit/issues/95

Fixing Mac shortcuts using the Control key instead of the Command Key

---

src/AvaloniaEdit/Editing/TextArea.cs

Instead of `TextArea` using its own `_scrollInvalidated` handler, use the `ILogicalScrollable` that the `TextArea` already has so that scroll invalidation calls are updated properly. The `ILogicalScrollable` is the internal `TextView`, which helps handle rendering, so then all the UI updates nicely.
Closes #105.

Use logical scrollable to invalidate scroll in TextArea

---

src/AvaloniaEdit/TextEditor.cs

This PR simply re-enables `ScrollToEnd()` and `ScrollToHome()` in `TextEditor`. Those methods exist on `ScrollViewer` (although I think they didn't at some point), so I can't think of a reason why they shouldn't be allowed again. 😄

Re-enable ScrollToEnd and ScrollToHome in TextEditor

---

src/AvaloniaEdit/Highlighting/HighlightingColor.cs
src/AvaloniaEdit/Highlighting/HighlightingColorizer.cs
src/AvaloniaEdit/Highlighting/Resources/MarkDownWithFontSize-Mode.xshd
src/AvaloniaEdit/Highlighting/Resources/ModeV2.xsd
src/AvaloniaEdit/Highlighting/Resources/Resources.cs
src/AvaloniaEdit/Highlighting/Xshd/V2Loader.cs
src/AvaloniaEdit/Highlighting/Xshd/XmlHighlightingDefinition.cs
src/AvaloniaEdit/Highlighting/Xshd/XshdColor.cs

Ported from https://github.com/icsharpcode/AvalonEdit/commit/a49d3fdbcfc02487da8a7dc6207ab35c775a859a.

Port of font family & font size highlighting support from AvalonEdit

---

src/AvaloniaEdit/Editing/CaretLayer.cs
src/AvaloniaEdit/Highlighting/HighlightingBrush.cs

`HighlightingBrush.GetColor` often returns null even though static colors is used.
The reason is that `HighlightingBrush.GetBrush` may return `ImmutableSolidColorBrush` and` GetColor` only checks `SolidColorBrush`.
This PR enable `GetColor` to use ImmutableSolidColorBrush, which inherits ISolidColorBrush.

Change typecheck from SolidColorBrush to ISolidColorBrush

---

src/AvaloniaEdit/Rendering/TextView.cs

When calling GetOrConstructVisualLine, the new line is added to the `_allVisualLines` collection. This causes the `_visibleVisualLines` collection to change. Imagine the following example
_visibleVisualLines has the following lines:
```
line5
line6
line7
line8
line9
```
Now suppose you build and `GetOrConstructVisualLine` line 2. The visual `_visibleVisualLines` collection ends having the following contents:
```
line5
line6
line7
line8
line9
line2
```
Taking a look at the original [avalonedit's TextView](https://github.com/icsharpcode/AvalonEdit/blob/master/ICSharpCode.AvalonEdit/Rendering/TextView.cs), when creating the `ReadonlyCollection `for the `_visibleVisualLines` it doesn't wrap a collection over the `_allVisualLines`.
It uses `.ToArray()` to make the `_visibleVisualLines `to be a …

Avoid corrupting VisibleVisualLines when calling GetOrConstructVisualLine

---

src/AvaloniaEdit/TextEditorOptions.cs

Obviously, the default value is true, not false.

Fix comment for AllowScrollBelowDocument property

---

src/AvaloniaEdit/Rendering/TextView.cs

Code ported from WPF upstream.
closes #142

Fix AvaloniaEdit when collapsing external controls

---

src/AvaloniaEdit/Rendering/TextView.cs

This fixes bug when caret position was sometimes displayed in wrong place, while document lines where slightly off position.
This change matches with original AvalonEdit: https://github.com/icsharpcode/AvalonEdit/blob/master/ICSharpCode.AvalonEdit/Rendering/TextView.cs#L1186

Fix #99, cursor position for last line displays below last line

---

src/AvaloniaEdit/TextEditor.xaml

In the TextEditor control template, background wasn't set, therefore you couldn't set control background using Background property.
This change matches original AvalonEdit: https://github.com/icsharpcode/AvalonEdit/blob/master/ICSharpCode.AvalonEdit/TextEditor.xaml#L14

Fix background color in template

---

src/AvaloniaEdit/Rendering/TextView.cs

Our code doesn't match upstream https://github.com/icsharpcode/AvalonEdit/blob/master/ICSharpCode.AvalonEdit/Rendering/TextView.cs#L1185
Also fixes that problem on 175% DPI
closes #147

Fix scroll after resize with 125% DPI

---

src/AvaloniaEdit/Search/SearchPanel.cs
src/AvaloniaEdit/Search/SearchPanel.xaml

Closes #155.
When calling BringCaretToView, take into account the height of the search panel and give that margin (plus an extra line height) to ensure that the search result is visible.

Fixed search results appearing under the search panel

---

src/AvaloniaEdit/Editing/RectangleSelection.cs

This PR fixes the following scenario:
1. Paste the content of this [sample-file.txt](https://github.com/AvaloniaUI/AvaloniaEdit/files/7560976/sample-file.txt) in the AvaloniaEdit window.
2. Go to line 25, column 12 (the beginning of the line).
3. Pres <kbd>Alt</kbd> + <kbd>Shift</kbd> + <kbd>Down</kbd> 4 times to make a multiline selection to line 29.
4. Type something.
Actual results: The caret goes to line 1.
Expected results: The caret maintains in line 29.

Fixed the caret position when multiline editing

---

src/AvaloniaEdit/Editing/CaretNavigationCommandHandler.cs
src/AvaloniaEdit/Editing/TextAreaDefaultInputHandlers.cs

We noticed that AvaloniaEdit doesn't define osx-specific keybinding for editing commands, for example:
* <kbd>Cmd</kbd> + <kbd>left</kbd>/<kbd>right</kbd> arrow: 
* **Expected behavior**: cursor moves to the start/end of the line
* **Actual behavior**: cursor moves one character left/right
* <kbd>Option</kbd> + <kbd>left</kbd>/<kbd>right</kbd> arrow:
* **Expected behavior**: cursor moves to the start/end of the previous/next word 
* **Actual behavior**: cursor moves one character left/right
This PR uses the Avalonia `PlatformHotkeyConfiguration` to set up the AvaloniaEdit's editing keybindings.

Fix osx-specific key shortcuts

---

src/AvaloniaEdit/Text/TextLineImpl.cs
src/AvaloniaEdit/Text/TextLineRun.cs
src/AvaloniaEdit/Text/TextRunProperties.cs
test/AvaloniaEdit.Tests/AvaloniaMocks/MockFontManagerImpl.cs
test/AvaloniaEdit.Tests/AvaloniaMocks/MockGlyphTypeface.cs
test/AvaloniaEdit.Tests/AvaloniaMocks/TestServices.cs
test/AvaloniaEdit.Tests/AvaloniaMocks/UnitTestApplication.cs
test/AvaloniaEdit.Tests/Editing/ChangeDocumentTests.cs

This PR makes empty lines have the same height normal lines have.
AvaloniaEdit assigned different heights for empty lines and nonempty lines.
The reason is that when creating TextLines with no runs (empty lines), the **extra +2 pixels for underlining was not being added**.
Refactored how LineHeight and BaseLine values are calculated to a commonplace, and use the same source code when calculating the height for empty and for non-empty lines.

Fixed empty lines height

---

src/AvaloniaEdit.Demo/MainWindow.xaml.cs
src/AvaloniaEdit/Editing/SelectionMouseHandler.cs
src/AvaloniaEdit/Editing/TextArea.cs

Originally it was requested by @danipen 
This feature is not present in the original AvaloniaEdit but it would not be bad if we add that IMO. It is what 90% of text editors do.

You should be able to move caret by right clicking text area

---

src/AvaloniaEdit/Editing/SelectionMouseHandler.cs

Triple-click should select the whole line but before this PR it wasn't working.
**Note**: this code is ported from AvalonEdit

Fix triple click

---

src/AvaloniaEdit/Editing/EditingCommandHandler.cs

if text is empty should not be copied, "\n" is not empty string so it will copied.

Ignore empty line copy

---

src/AvaloniaEdit.Demo/MainWindow.xaml
src/AvaloniaEdit.Demo/MainWindow.xaml.cs
src/AvaloniaEdit.TextMate/AvaloniaEdit.TextMate.csproj
src/AvaloniaEdit/Rendering/LinkElementGenerator.cs
src/AvaloniaEdit/Rendering/VisualLine.cs
src/AvaloniaEdit/Text/TextLineImpl.cs
src/AvaloniaEdit/Text/TextLineRun.cs

**This PR allows AvaloniaEdit to handle long lines with acceptable performance.** 
Before this PR, AvaloniaEdit only supported lines no longer than 10.000 characters. If a line in the document was longer than 10.000 characters, an exception was raised.
Before this PR, removing that restriction, AvaloniaEdit is able to display longer lines, but some issues appear:
- The TextMate tokenizer was slow for super long lines.
- Editing, navigating, selecting text, etc ... was quite slow.
- There is a accumulated error between the position a glyph is drawn and the position the caret is.
- In general performance was quite bad with really long lines (>250.000) characters.
I made several changes to better support very long lines:
- **Fixed the accumulated error between the glyph position and the …

Improve long lines support

---

src/AvaloniaEdit.TextMate/AvaloniaEdit.TextMate.csproj

If fixes a NRE exception when trying to revalidate tokens when the tokenizer is still null.

Update TextMateSharp to v1.0.15

---

src/AvaloniaEdit.TextMate/TextMateColoringTransformer.cs

Theme definitions use #RRGGBBAA and Avalonia parses colors using #AARRGGBB.

Normalize theme color strings before parsing them

---

src/AvaloniaEdit/Rendering/SingleCharacterElementGenerator.cs
src/AvaloniaEdit/Text/TextLineRun.cs
test/AvaloniaEdit.Tests/AvaloniaMocks/MockGlyphTypeface.cs
test/AvaloniaEdit.Tests/Text/TextLineRunTests.cs

Fixes #191. Now displaying tabs, spaces, or newline characters doesn't add spacing between lines.
Demo (notice I draw the RextRun bounding boxes as debug purposes to ensure that they are correct):
https://user-images.githubusercontent.com/501613/151114591-829ec35a-6186-4a77-b66c-144a380cdc00.mp4

Fix embedded runs baseline

---

src/AvaloniaEdit.Demo/Resources/SampleFiles/text.log
src/AvaloniaEdit.TextMate/GenericLineTransformer.cs
src/AvaloniaEdit.TextMate/TextMateColoringTransformer.cs
src/AvaloniaEdit.TextMate/TextTransformation.cs

This PR enables TextMate integration to draw bold, italic, or underline font for certain tokens. 
Some examples:
This PR also fixes an index in the `GenericLineTransformer.cs` that prevented to colorize the last line in the document.

Textmate - support bold, italic and underline font styles

---

Directory.Build.props

Fixes #199.
When the `TextEditorModel` reports a certain number of lines and the TextMate tokenizer thread tries to parse a line that not is in the range reported by the `TextEditorModel` ([0-TextEditorModel.GetNumberOfLines()), it caused an IndexOutOfRangeException in TextMateSharp. 
This was fixed in TextMateSharp 1.0.24. This PR update the dep to that version.

Update to TextMateSharp 1.0.24

---

src/AvaloniaEdit.Demo/MainWindow.xaml
src/AvaloniaEdit/Text/StringRange.cs
src/AvaloniaEdit/Text/TextLineImpl.cs
src/AvaloniaEdit/Text/TextLineRun.cs
src/AvaloniaEdit/TextEditor.cs
test/AvaloniaEdit.Tests/AvaloniaMocks/MockFormattedTextImpl.cs
test/AvaloniaEdit.Tests/AvaloniaMocks/MockPlatformRenderInterface.cs
test/AvaloniaEdit.Tests/AvaloniaMocks/TestServices.cs
test/AvaloniaEdit.Tests/Rendering/TextViewTests.cs
test/AvaloniaEdit.Tests/Text/TextLineImplTests.cs
test/AvaloniaEdit.Tests/Text/TextLineRunTests.cs

Fixes #205.
Sometime this year we will change AvaloniaEdit text API to use Avalonia's TextFormatter API. In the meantime, I fixed the existing codebase. This PR fixes and extends the existing word-wrap implementation:
- Fixed the `TextLineImpl `to not add a run that doesn't fit the `widthLeft`.
- Added support for word wrapping in the `TextLineRun`.
- Automatically disable the horizontal scroll when setting `WordWrap=True`
Some demo.
https://user-images.githubusercontent.com/501613/153749514-2450e042-1b5b-4934-a3d4-aeb4f00090dd.mp4

Fix word wrap

---

src/AvaloniaEdit.TextMate.Grammars/RegistryOptions.cs

Some TM languages don't define language.Extensions, protect it.

Fix NRE in TM language extensions

---

Directory.Build.props
src/AvaloniaEdit.TextMate/DocumentSnapshot.cs
src/AvaloniaEdit.TextMate/TextEditorModel.cs
test/AvaloniaEdit.Tests/TextMate/DocumentSnapshotTests.cs

This PR fixes an `IndexOutOfRangeException` when replacing text in the Editor using the following shortcut keys:
- Copy text to the clipboard from another text source.
- Go back to AvaloniaEdit.
- Select <kbd>Ctrl + A</kbd> to select all text.
- Hit <kbd>Ctrl + V</kbd> to paste that text.
In the time-lapse between the events `DocumentOnChanging` and `DocumentOnChanged`, the TMModel still asked for old lines with old LineRanges (offset + len) which caused AvaloniaEdit to fail when getting the text from the rope.
Now it's fixed.

Fixed index out of range replacing text

---

src/AvaloniaEdit/CodeCompletion/CompletionWindowBase.cs

about https://github.com/AvaloniaUI/AvaloniaEdit/issues/194.
In Avalonia 0.10.11, Avalonia [observes the position of the popup parent](https://github.com/AvaloniaUI/Avalonia/blob/089fda0dc7fedd67ed6a4febd2be8c843760eb55/src/Avalonia.Controls/Primitives/Popup.cs#L430), and moves popup accordingly.
Currently, `CompletionWindowBase` dosen't change `PlacementTarget`. This causes that the position of the popup parent is treated as a position of the popup ([L380](https://github.com/AvaloniaUI/Avalonia/blob/089fda0dc7fedd67ed6a4febd2be8c843760eb55/src/Avalonia.Controls/Primitives/Popup.cs#L380) and [L388](https://github.com/AvaloniaUI/Avalonia/blob/089fda0dc7fedd67ed6a4febd2be8c843760eb55/src/Avalonia.Controls/Primitives/Popup.cs#L388)).
So …

fix the wrong complete window position

---

src/AvaloniaEdit/Search/SearchPanel.cs
src/AvaloniaEdit/TextEditor.cs

Expose the `SearchPanel` in the `TextEditor` so users can, manage the search panel programmatically (for example, show, hide, change the search term, etc ...).
Additionally, fixed an issue with the search panel control template. When the search panel was visible, and then you detached the `TextEditor` from the logical tree, and you attached it later (i.e moving the control from one panel to another), the SearchPanel's control template was lost. I fixed it by closing the SearchPanel when detaching from the logical tree and restoring it if needed when attaching.

Expose the search panel in the TextEditor

---

Directory.Build.props

This new version includes:
- Fixes Operations that change non-concurrent collections must have exclusive access: https://github.com/danipen/TextMateSharp/pull/16
- Use .net 6.0 for building the nugets: https://github.com/danipen/TextMateSharp/pull/17

Update Textmatesharp to 1.0.34

---

Directory.Build.props

Enables TextMateSharp x86 architecture.

Update to TextMateSharp 1.0.38

---

src/AvaloniaEdit.Demo/MainWindow.xaml.cs
src/AvaloniaEdit/Text/TextLineRun.cs

Strikethrough lines are not displayed in macOS.
The reason is that the glyphTypeface's `StrikethroughThickness `and `StrikethroughPosition ` in macOS are 0 (**note that this is working ok in Windows OS**).
This PR also adds some underline and strikethrough sample text to the sample application.

Fix strikethrough in macOS

---

src/AvaloniaEdit/Editing/EditingCommandHandler.cs
src/AvaloniaEdit/Editing/TextArea.cs
src/AvaloniaEdit/TextEditor.cs

Expose some properties like:
- CanCopy
- CanCut
- CanPaste
- CanDelete
- CanSelectAll
- CanSearch
to be queried so any implementation for a ContextMenu for an editor can query these properties to set up the menu item enablement.

Expose properties for context menus

---

src/AvaloniaEdit/Rendering/BackgroundGeometryBuilder.cs

This PR aligns the position of the selection with the position of the caret. 
The `Caret` is using the `VisualYPosition.TextTop` to calculate the position. So also use that method to calculate the `VisualYPosition` for a line when calculating the `y` position of the selection rectangle.

Align the selection rectangle top position with the caret top position

---

src/AvaloniaEdit.TextMate/TextMateColoringTransformer.cs
src/AvaloniaEdit/Editing/TextArea.cs
src/AvaloniaEdit/Folding/FoldingManager.cs
src/AvaloniaEdit/Highlighting/HighlightingColorizer.cs
src/AvaloniaEdit/Rendering/TextView.cs

Removed the deferred `InvalidateMeasure` call.
- No noticeable change in performance (tested with and without it in macOS and windows, and no perf changes).
- It obscures the API usage. Basically, when you want/need to access the VisualLines you need to use the Dispatcher too (you need to wait until at least until the control has completed a measuring cycle to ensure that the visual lines have been generated). The same thing happens for scrolling, after scrolling you need to defer any op until the visual lines have been generated. Removing it would make all usages easier since it would be always synchronous. Virtualization makes things fast enough in my opinion.

Remove the deferred InvalidateMeasure

---

src/AvaloniaEdit/Rendering/TextView.cs

Previously each VisualLine was recreated on selection change which isn't needed and caused empty visuals for some frames.

Fix VisualLine selection flicker

---

src/AvaloniaEdit/AvaloniaEdit.csproj

Hi,
I was doing some tests with AvaloniaEdit and Avalonia.FuncUI and wondered if the System.Xml.ReaderWriter nuget package reference is needed when targetting netstandard2.0 (System.Xml being built in to that version).
(Reasoning: the security tools at work like to complain about indirect references to old versions of System.Text.RegularExpressions that have security vulnerabilities and I got in a habbit of removing old references if they don't seem to be required any more)

Try building without the System.Xml.ReaderWriter nuget package reference

---

src/AvaloniaEdit/Editing/Caret.cs
src/AvaloniaEdit/Editing/LineNumberMargin.cs
src/AvaloniaEdit/Editing/SelectionMouseHandler.cs
src/AvaloniaEdit/Rendering/TextView.cs
src/AvaloniaEdit/TextEditor.cs

This PR fixes the `AllowScrollBelowDocument` option. The event chain in the ScrollViewer prevented AvaloniaEdit to reserve more space for the viewport, because when the scrollbar reached the max viewport no new events sent, so the code did not work as WPF.
After these fixes, when the option `AllowScrollBelowDocument` is enabled, the TextView adds an extra height of `Bounds.Height - DefaultLineHeight` so the user is able to scroll. We ensure that at least one line is visible.
I also removed the margins used when the TextEditor is clicked, or the line is being edited. It used a margin of 5px for mouse clicks and a 30px margin when editing text. This helps to maintain the scroll more stable when editing or clicking the textView in the edges.
Some demo: …

Fix allow scroll below document

---

src/AvaloniaEdit/Editing/SelectionMouseHandler.cs
src/AvaloniaEdit/TextEditorOptions.cs

This is useful when the textbox adds some scroll animations on pointer down, which causes unwanted selections when the mouse button is released.
Note that Visual Studio (and Visual Studio Code) don't update the selection on mouse up, so the option makes sense.

Add an option to avoid extend selection on mouse up

---

src/AvaloniaEdit/Rendering/TextView.cs
src/AvaloniaEdit/Rendering/VisualLine.cs

This PR introduces a fix that removes a VisualLineDrawingVisual from the logical tree on VisualLine.Dispose

Fixes VisualLine leak

---

src/AvaloniaEdit/Rendering/VisualLineText.cs

Attempt to prevent folding crashes

---

src/AvaloniaEdit/Rendering/SingleCharacterElementGenerator.cs
src/AvaloniaEdit/Rendering/TextViewCachedElements.cs
src/AvaloniaEdit/Rendering/VisualLineTextSource.cs
src/AvaloniaEdit/TextEditorOptions.cs

This PR allows to configure the control chars displayed for spaces, tabs and EOL, via `TextEditorOptions`:
- **ShowSpaces**: Default character is `·`.
- **ShowTabs**: Default character is `→`.
- **ShowEndOfLine**:
- _CRLF_: Default character is `¶`.
- _CR_: Default character is ` \r`.
- _LF_: Default character is ` \n`.
Additionally, this PR displays the EOL chars with smaller font size, to make the EOL glyphs less conspicuous, they were too big.
**Example**: Setting the following configuration for the demo application:
```
_textEditor.Options.ShowSpacesGlyph = "o";
_textEditor.Options.ShowTabsGlyph = ">";
_textEditor.Options.EndOfLineCRGlyph = "CR";
_textEditor.Options.EndOfLineLFGlyph = "LF";
_textEditor.Options.EndOfLineCRLFGlyph = "CRLF";
```
Displays the control characters in the …

Make control characters configurable

---

src/AvaloniaEdit.Demo/MainWindow.xaml
src/AvaloniaEdit.Demo/MainWindow.xaml.cs
src/AvaloniaEdit/Rendering/ColumnRulerRenderer.cs
src/AvaloniaEdit/Rendering/TextView.cs
src/AvaloniaEdit/TextEditorOptions.cs

- Allow multiple-column rulers instead of only one.
- Improve the foreground color.
- Add a sample to the demo project.
Demo:

Allow multiple column rulers

---

src/AvaloniaEdit/Editing/SelectionMouseHandler.cs

Taking a look at the upstream project, it seems that the code doesn't belong there. 
Additionally, protect the code to avoid call `GetTextLineByVisualYPosition` when the VisualLines have not been set yet.
Fixes #276

Fix triple click causes NRE

---

src/AvaloniaEdit.TextMate/TextMateColoringTransformer.cs

Fixed a condition that caused that some lines were not highlighted until they were re-created.
- Open a document of, let's say 500 lines and go to line 400 (visible range is 400-450).
- Open a document of 100 lines (first line is visible).
- When the `TMModel` starts to emit tokens, the visual lines haven't been constructed yet.
So `_firstVisibleLineIndex` and `_lastVisibleLineIndex` are not updated and still 400 and 450. So this condition avoids not post to the dispatcher the redraw
```csharp
bool changedLinesAreNotVisible =
(firstChangedLineIndex < _firstVisibleLineIndex && lastChangedLineIndex < _firstVisibleLineIndex) ||
(firstChangedLineIndex > _lastVisibleLineIndex && lastChangedLineIndex > _lastVisibleLineIndex);
if (changedLinesAreNotVisible)
return;
```
**Solution:**
Just …

Fixed lines not be highlighted sometimes

---

src/AvaloniaEdit/Utils/ExtensionMethods.cs

When the control is not effectively visible the matrix could be null

---

src/AvaloniaEdit/TextEditorOptions.cs

Use `nameof` instead of a literal string to avoid mismatched names, and make refactors easier in the future.

Improve PropertyChanged naming

---

src/AvaloniaEdit/Search/SearchPanel.cs
src/AvaloniaEdit/TextEditor.cs

Fixes #315.
Set `SearchPanel.IsReplaceMode` to `false` when the `TextEditor.IsReadonly` is set to `true`. This causes the replace part of the search panel to be hidden when the editor is set to read only.

Fix is replace mode

---

Directory.Build.props
src/AvaloniaEdit.Demo/MainWindow.xaml.cs
src/AvaloniaEdit/CodeCompletion/CompletionList.cs
src/AvaloniaEdit/CodeCompletion/CompletionWindow.cs
src/AvaloniaEdit/CodeCompletion/CompletionWindowBase.cs
src/AvaloniaEdit/Editing/Caret.cs
src/AvaloniaEdit/Editing/TextArea.cs
src/AvaloniaEdit/Rendering/BackgroundGeometryBuilder.cs
src/AvaloniaEdit/Rendering/SingleCharacterElementGenerator.cs
src/AvaloniaEdit/Rendering/TextView.cs
test/AvaloniaEdit.Tests/AvaloniaMocks/MockFontManagerImpl.cs
test/AvaloniaEdit.Tests/AvaloniaMocks/MockGlyphRun.cs
test/AvaloniaEdit.Tests/AvaloniaMocks/MockGlyphTypeface.cs

I am leaving this here because I tried to upgrade it and while everything seemed fine and builds, I am hitting a very bad performance issue which profiling seems to suggests that the GC is put under a lot of pressure which didn't happen with preview5. The CPU usage is much higher than it should and the app becomes very unresponsive.
Just in case I can't get anywhere so my branch is there.

Upgrade to Avalonia 11.0.0-preview6

---

src/AvaloniaEdit.TextMate/AvaloniaEdit.TextMate.csproj
src/AvaloniaEdit/AvaloniaEdit.csproj

I was browsing nuget.org and noticed the generic desciptions fields on the packages:
So I thought I'd grab some text off the readme and add it as something a bit more useful, but then I noticed that the nuget.org listings don't specify what the license is, so I added PackageLicenseExpressions as well

Add descriptions and license expressions to the nuget packages

---

Directory.Build.props

- Update TextMateSharp: the new version uses System.Text.Json instead of Newtonsoft.Json, and also brings trimming+AOT support

Update TextMateSharp and drop Newtonsoft.Json

---

src/AvaloniaEdit/Utils/IServiceContainer.cs

WPF version allows to add other services into text editor, which was heavily used in our code
```csharp
TextEditor editor = ...;
editor.GetService<IServiceContainer>().AddService<MyServiceType>();
```

Expose IServiceContainer

---

src/AvaloniaEdit/Document/DocumentChangedEventArgs.cs
src/AvaloniaEdit/Editing/TextArea.cs
src/AvaloniaEdit/Rendering/TextView.cs
src/AvaloniaEdit/TextEditor.cs
src/AvaloniaEdit/TextEditorComponent.cs

Sometimes one requires to subscribe to events existing inside the `TextDocument` and maybe you're interested in unsubscribing the events in the old document before subscribing to the events in the new document.
For that purpose, I just extended the `EventArgs` used for the `DocumentChanged` event to pass the old document and the new document.

Pass the old new TextDocument on the DocumentChanged event

---

src/AvaloniaEdit.Demo/MainWindow.xaml.cs
src/AvaloniaEdit/CodeCompletion/ICompletionData.cs

I propose changing `ICompletionData.Image` from `Bitmap` to `IImage`. Having `Bitmap` in the interface is unnecessarily restrictive. Changing the type to `IImage` allows other types of image sources. For example: `CroppedBitmap`, `DrawingImage`
In my case, I have an icon font that has a custom `IImage` implementation.
⚠ Note that this is a breaking change! Any application implementing `IComplectionData` (like AvaloniaEdit.Demo) will have to be updated. However, I think that this change is worthwhile and should be made before releasing 11.0.0.

Change ICompletionData.Image from Bitmap to IImage

---

src/AvaloniaEdit/Rendering/TextView.cs

**Problem:**
The `TextLayer` is rendered behind the `SelectionLayer`, which makes the text hard to read when selected. If you style the control and set an opaque `SelectionBrush` then the text is obscured completely.
**Cause:**
The problem is that `TextView.Layers` and `TextView.VisualChildren` are out of sync: 
The `Layers` are 
1. `SelectionLayer`
1. `TextLayer`
1. `CaretLayer`
but the `VisualChildren` are
1. `TextLayer`
1. `SelectionLayer`
1. `CaretLayer`
**Fix:**
The `LayerCollection` needs to insert the control at the correct index. (The first *n* visual children should correspond to the *n* layers in the `LayerCollection`.)

Fix: TextLayer is rendered behind SelectionLayer

---

src/AvaloniaEdit.Demo/App.xaml
src/AvaloniaEdit/CodeCompletion/CompletionList.xaml
src/AvaloniaEdit/CodeCompletion/CompletionWindow.cs
src/AvaloniaEdit/CodeCompletion/PopupWithCustomPosition.cs
src/AvaloniaEdit/Themes/Fluent/Base.xaml
src/AvaloniaEdit/Themes/Simple/Base.xaml

**Problem:**
The default `CompletionList` style is broken. It currently works in `AvaloniaEdit.Demo` because the style is overridden in `App.xaml`. When removing the style in `App.xaml`, it looks like this:
The tooltip position is also off.
**Fix:**
I removed the style from `App.xaml` and fixed the default style in `CompletionList.xaml`.
I also fixed the tooltip positioning in `CompletionWindow.cs`.
Tested with with the following themes: Fluent/Light, Fluent/Dark, Simple/Light, Simple/Dark

Fix: CompletionList style is broken.

---

src/AvaloniaEdit/Rendering/CurrentLineHighlightRenderer.cs
src/AvaloniaEdit/Rendering/TextView.cs

**Problem:**
The vertical column ruler is rendered behind the current line highlight.
**Fix:**
I suggest changing `CurrentLineHighlightRenderer.Layer` to `KnownLayer.Background`. This way, the vertical column ruler and other highlights (such as search result markers) can be rendered on top.
In `TextView` the `ColumnRulerRenderer` needs to be registered after the `CurrentLineHighlightRenderer`.
Also fixed a typo in the existing code.

Fix: Column ruler behind current line highlight

---

src/AvaloniaEdit/CodeCompletion/CompletionListBox.cs
src/AvaloniaEdit/CodeCompletion/CompletionWindowBase.cs

This PR replaces `IStyleable` with `StyleKeyOverride` to remove the warnings.
`IStyleable` is deprecated in Avalonia UI 11.0.0 RC1. See https://github.com/AvaloniaUI/Avalonia/wiki/Avalonia-11-Porting-Guide#optional-but-recommended.

Fix CS0618: Interface 'Avalonia.Styling.IStyleable' is obsolete

---

src/AvaloniaEdit/Editing/TextArea.cs

This pull request fixes issue #359 . It uses default TextSelection(0, 0) for the case when TextArea is null, and thus prevents NRE.
I tested this a bit and it looks like it does not break things.

Fix NRE on losing focus #359

---

Directory.Build.props
test/AvaloniaEdit.Tests/WeakReferenceTests.cs

No changes. Just use the new version.
@maxkatz6 please note that the `WeakReferenceTests.cs` were not migrated to the headless platform. I changed to migrate them, but they are not passing anymore in the headless platform. Please, take a look if you want to re-enable them.

Migrate to Avalonia 11.0.4

---

Directory.Build.props

AOT requires using TextMateSharp 1.0.56+, otherwise it will fail to load grammar definitions.
I would like to see a new version of AvaloniaEdit being released soon to fix this AOT issue.

Bump dependency version

---

src/AvaloniaEdit/CodeCompletion/CompletionWindow.cs

I noticed in some cases with long completionlists this does not work well, I will try to find another way.
When scrolling down the tooltip position cannot always be taken from the container, because the container is not always generated at this point. I fixed this by simply placing the tooltip to the bottom whenever this happens.

[WIP] Fix Completion Tooltip Placement

---

src/AvaloniaEdit/Editing/SelectionMouseHandler.cs
src/AvaloniaEdit/Search/SearchPanel.cs

more details : 
https://github.com/AvaloniaUI/AvaloniaEdit/discussions/388

Fix scrolling by mouse selection

---

src/AvaloniaEdit/Search/SearchPanel.cs
test/AvaloniaEdit.Tests/AvaloniaMocks/UnitTestApplication.cs
test/AvaloniaEdit.Tests/Search/FindTests.cs
test/AvaloniaEdit.Tests/Search/SearchPanelTests.cs

If you had a text that contains multiple matches and replace one by one using the "Replace next" button it skips one of the matches each time (see #355).
Changes on this PR:
* Re-enable existing (but commented) `FindTests`.
* Added unit tests to cover this functionality.
* Fixes #355.

Fix replace next functionality

---

src/AvaloniaEdit.Demo/MainWindow.xaml.cs
src/AvaloniaEdit/Editing/TextArea.cs

This PR enables *Overstrike* mode (in other editors called *OVR, Overwrite, Overtype*), which is not yet working.
Simply uncommenting the code in *TextArea.cs* solves the problem. All relevant code paths for Overstrike from AvalonEdit are already present in AvaloniaEdit.
Instruction for testing:
- Run *AvaloniaEdit.Demo*.
- Press `Insert` (`ins`) key on the keyboard.
Expected behavior:
- The caret changes from a line to block.
- Typing now overwrites the right characters instead of inserting characters at the caret position.

Enable overstrike mode

---

src/AvaloniaEdit.Demo/CustomMargin.cs
src/AvaloniaEdit.Demo/MainWindow.xaml.cs

This PR adds a custom margin to the text editor demo. It behaves like the *breakpoint margin* in Visual Studio. A gray circle is rendered when the mouse is over the margin and a red circle is rendered when the margin is clicked.
Screenshot:

Add custom, clickable margin in demo

---

AvaloniaEdit.sln
src/AvaloniaEdit.Demo/App.xaml.cs
src/AvaloniaEdit.Demo/AvaloniaEdit.Demo.csproj
src/AvaloniaEdit.Demo/CustomMargin.cs
src/AvaloniaEdit.Demo/MainWindow.xaml
src/AvaloniaEdit.Demo/MainWindow.xaml.cs
src/AvaloniaEdit.Demo/ViewModels/MainWIndowViewModel.cs
src/AvaloniaEdit.Demo/ViewModels/ThemeViewModel.cs
src/AvaloniaEdit.TextMate/AvaloniaEdit.TextMate.csproj
src/AvaloniaEdit.TextMate/TextMate.cs
src/AvaloniaEdit.TextMate/TextMateColoringTransformer.cs
src/AvaloniaEdit.TextMate/TextTransformation.cs
src/AvaloniaEdit/Rendering/CurrentLineHighlightRenderer.cs
src/AvaloniaEdit/Rendering/TextView.cs

- Little bit of MVVP in here to enable bindings in the AXAML
- Drop down, allows me to look at specific themes, As I intend to leverage a little more of the info from the TextMateSharp JSON's
HELLO, I'm the author of BlitzSearch ( https://natestah.com ).  I'm making heavy use of AvaloniaEdit and there are things that I want to do with it.  This would be a small Ice Breaker change, would be awesome if the efforts could align.

Change Theme to a DropDown with flyout 

---

src/AvaloniaEdit.TextMate/TextMateColoringTransformer.cs
src/AvaloniaEdit.TextMate/TextTransformation.cs

- CS0266 Cannot implicitly convert type 'int' to 'TextMateSharp.Themes.FontStyle'
- CS0019 Operator '!=' cannot be applied to operands of type 'FontStyle' and 'int'
- CS0019 Operator '&' cannot be applied to operands of type 'FontStyle' and 'int'

fix: Compile Issue

---

src/AvaloniaEdit.TextMate/Compatibility/Math.cs
src/AvaloniaEdit.TextMate/TextEditorModel.cs

fix: System.NullReferenceException on Undo

---

src/AvaloniaEdit.TextMate/AvaloniaEdit.TextMate.csproj

Bumps TextMateSharp version to latest, which allows usage of changes from https://github.com/danipen/TextMateSharp/pull/67

Bump TextMateSharp version

---

src/AvaloniaEdit.Demo/CustomMargin.cs

Fixes #442.
- Fixed custom margin rendering visuals in the wrong position when scrolling.
- Added `InvalidateVisual()` when the pointer exits to hide the hovered marker.
- Cleared markers when changing the document.

Fix customMargin renders incorrectly when scrolling

---

src/AvaloniaEdit.Demo/MainWindow.xaml
src/AvaloniaEdit.Demo/MainWindow.xaml.cs
src/AvaloniaEdit.Demo/ViewModels/MainWIndowViewModel.cs

hello 
this is a PR fixing Commands of Mouse ContextMenu for AvaloniaEdit.Demo
used ContextFlyout instead of ContextMenu
previous actions which were not working:
now these Items working (it's not ReactiveUI, basic MVVM):
couldn't find a better way to call the Commands from Demo. but this seems working just fine .in that case let me know here,
PS:   it's my very first PR 😅, hope it helps and more importantly hope i've done it the right way

Mouse ContextFlyout commands fix in AvaloniaEdit.Demo

---

src/AvaloniaEdit/Rendering/VisualLine.cs

Having documents with very long lines, 1M columns or so (this can happen for minified json or javascript) caused the UI to stop running.

Do not run the element generators for performance reasons

---

src/AvaloniaEdit.Demo/MainWindow.xaml.cs
src/AvaloniaEdit/CodeCompletion/CompletionList.cs
src/AvaloniaEdit/CodeCompletion/CompletionWindow.cs

- Makes the CompletionList selection circular.
- Fixes a virtualization issue.
- Allows the completion window to grow dynamically (due to virtualization), constraining the MinWidth so once the popup gets wider, it never gets narrower again during that session.
Demo:
https://github.com/user-attachments/assets/b6b078be-6737-4b60-b7f4-475a16907b91

Completion window improvements

---

src/AvaloniaEdit.Demo/CustomMargin.cs

Protect NRE when you move the mouse near the edges and the VisualLine is null

Fixed NRE in custom margin

---

src/AvaloniaEdit.Demo/AvaloniaEdit.Demo.csproj
src/AvaloniaEdit.Demo/MainWindow.xaml.cs
src/AvaloniaEdit/Editing/EditingCommandHandler.cs
src/AvaloniaEdit/Editing/TextArea.cs
src/AvaloniaEdit/TextEditor.cs
src/AvaloniaEdit/TextEditorOptions.cs

This PR introduces a new option, `AcceptsTab`, similar to [Avalonia's TextBox.AcceptsTab](https://github.com/AvaloniaUI/Avalonia/blob/9cecb90ba1e681d1783e3a89db4b8d860859550f/src/Avalonia.Controls/TextBox.cs#L418) property. 
When disabled, this option allows the TextEditor to avoid consuming the `Tab` and `Shift+Tab` keys. This is particularly useful when `TextEditor` is used within a form, as users often expect the Tab key to navigate between fields. 
By default, `AcceptsTab` is set to true.

Added AcceptsTab option to TextEditor

---

src/AvaloniaEdit/Editing/CaretNavigationCommandHandler.cs
src/AvaloniaEdit/Editing/HotkeyConfiguration.cs
src/AvaloniaEdit/Editing/SelectionMouseHandler.cs

Pressing `Shift+Option+Arrow keys` didn't work in macOS because rectangular selection shadowed this keystroke combination (we were using Alt, which is equivalent to Option for rectangular selection on all platforms).
Now we use Control in the macOS platform for the rectangular selection so every command works as expected:
* `Shift+Option+Left/Right` now selects the next previous word.
* `Shift+Control+Up/Down` performs rectangular selection.
* `Control+Mouse selection` performs a rectangular selection with the mouse.
https://github.com/user-attachments/assets/7b878bf8-b346-45cd-8269-85fdaefc0fb3

Fixed BoxSelectionModifiers in macOS shadowing other keymaps

---

src/AvaloniaEdit/Editing/CaretNavigationCommandHandler.cs
src/AvaloniaEdit/Editing/EditingCommandHandler.cs
src/AvaloniaEdit/Editing/TextArea.cs
src/AvaloniaEdit/Search/SearchPanel.cs
src/AvaloniaEdit/Search/SearchPanel.xaml

This PR fixes #482.
Previously, when pressing the <kbd>Tab</kbd> key inside the `SearchPanel's` `TextBox`, the `TextArea` incorrectly handled the `OnKeyDown` event, marking it as handled. This prevented Avalonia’s built-in `KeyboardNavigation` system from processing the event correctly.
**Solution:**
Avoid processing the <kbd>Tab</kbd> key in the `TextArea` when it is not focused, allowing normal focus traversal.
Additionally, set the `KeyboardNavigationMode` to `Cycle` in the `SearchPanel` to ensure the focus stays within the panel when expected.
In our application, the following built-in `ApplicationCommands` were incorrectly handled by AvaloniaEdit instead of the `SearchPanel`'s `TextBox`:
- `ApplicationCommands.SelectAll`
- `ApplicationCommands.Cut`
- `ApplicationCommands.Copy`
- …

Fix SearchPanel keyboard navigation and shortcut handling

---

src/AvaloniaEdit/Editing/EditingCommandHandler.cs
src/AvaloniaEdit/Search/SearchPanel.cs
src/AvaloniaEdit/Search/SearchPanel.xaml

Fix the `EditingCommandHandler`: The context menu actions (copy/cut/paste) didn't work because the TextArea is not focused when executing those actions from the context menu.

Copy/Cut/Paste don't work from the context menu

---

src/AvaloniaEdit/Rendering/TextView.cs

Fixes a crash that can occur when deleting large text with line numbers enabled.

Fix visual line crash when deleting text with line numbers

---

src/AvaloniaEdit/Editing/CaretNavigationCommandHandler.cs

Ports the upstream fix https://github.com/icsharpcode/AvalonEdit/pull/140 to AvaloniaEdit.
Fixes #428

Fix end key with trailing whitespace.

---

src/AvaloniaEdit.Demo/MainWindow.xaml.cs

When clicking `Add Button` in the `AvaloniaEdit.Demo`, some buttons are never drawn.
The `ElementGenerator` uses `BinarySearch` to find the first offset with a `Button`. But the list is never actually sorted in the demo.
Sort the list after each insert.

Fix: Buttons not drawn when unsorted

---

src/AvaloniaEdit/Rendering/BackgroundGeometryBuilder.cs

Fixes #472.
When a selection extends beyond the visual line into the "virtual space" then the `BackgroundGeometryBuilder` creates two segments per line. One for the visible text, and one for the virtual space.
The segment for the virtual space didn't apply the scroll offset. This is now fixed.

Fix: Rectangular selection ignores scroll offset

---

src/AvaloniaEdit.Demo/MainWindow.xaml.cs
src/AvaloniaEdit/CodeCompletion/CompletionAcceptAction.cs
src/AvaloniaEdit/CodeCompletion/CompletionList.cs
src/AvaloniaEdit/CodeCompletion/CompletionWindow.cs
src/AvaloniaEdit/CodeCompletion/CompletionWindowBase.cs
src/AvaloniaEdit/TextEditorOptions.cs

This PR adds an options to choose whether completion items are inserted on `PointerPressed`, `PointerReleased` or `DoubleTapped`.
This is an improvement on #414 and addresses the feedback by @gebodal mentioned on issue #413.
In addition, this fixes an issue where first click in the `CompletionWindow` is swallowed by the `PopupWithCustomPosition` tooltip.

Add option to insert completion item on PointerPressed/PointerReleased/DoubleTapped

---

src/AvaloniaEdit/Editing/Selection.cs

Fixes #427.
`AddSpacesIfRequired` incorrectly counts the line length when EOL markers are enabled.
The EOL marker itself shouldn't be counted.

Fix: Insert at wrong offset in virtual space with EOL glyphs

---

src/AvaloniaEdit/Editing/TextArea.cs
src/AvaloniaEdit/TextEditor.cs

With Consolonia we need to assign a custom brush to CaretBrush. The problem is that currently that's buried deep in TextArea.Caret.CaretBrush, which is not a styled property and can't be addressed via styles/themes.
This PR adds a StyledProperty **CaretBrush**  to TextArea and plumbs it through to the underlining object.

Add CaretBrush as DirectProperty on TextArea so it can be defined via markup

---

src/AvaloniaEdit/Folding/FoldingElementGenerator.cs
src/AvaloniaEdit/Rendering/SingleCharacterElementGenerator.cs

What has been fixed:
1. When turning on or off spaces the text will jump up and down (incorrect height).
2. When collapsing a foldable area the line height was changing.

fixed jumping / unaligned text with special characters and collapsed folding
