AvaloniaUI/AvaloniaEdit

src/AvaloniaEdit/Editing/TextArea.cs
src/AvaloniaEdit/Rendering/TextView.cs

Saved you a massive headache there!
Working scrolling!

Feature/ilogical scrolling (fixes #2)

---

src/AvaloniaEdit.Demo/MainWindow.xaml
src/AvaloniaEdit.Demo/MainWindow.xaml.cs
src/AvaloniaEdit/CodeCompletion/CompletionList.cs
src/AvaloniaEdit/CodeCompletion/CompletionList.xaml
src/AvaloniaEdit/CodeCompletion/CompletionListBox.cs
src/AvaloniaEdit/CodeCompletion/CompletionWindow.cs
src/AvaloniaEdit/CodeCompletion/CompletionWindowBase.cs
src/AvaloniaEdit/CodeCompletion/PopupWithCustomPosition.cs
src/AvaloniaEdit/Editing/TextArea.cs
src/AvaloniaEdit/Editing/TextAreaInputHandler.cs
src/AvaloniaEdit/Rendering/VisualLine.cs
src/AvaloniaEdit/Text/TextLineImpl.cs

Completion window

---

src/AvaloniaEdit.Demo/MainWindow.xaml.cs
src/AvaloniaEdit/AvaloniaEdit.xaml
src/AvaloniaEdit/CodeCompletion/CompletionList.xaml
src/AvaloniaEdit/CodeCompletion/CompletionWindow.cs
src/AvaloniaEdit/CodeCompletion/InsightWindow.cs
src/AvaloniaEdit/CodeCompletion/InsightWindow.xaml
src/AvaloniaEdit/CodeCompletion/OverloadViewer.cs
src/AvaloniaEdit/Text/TextLineImpl.cs

Insight window

---

src/AvaloniaEdit.Demo/AvaloniaEdit.Demo.csproj
src/AvaloniaEdit/AvaloniaEdit.csproj
src/AvaloniaEdit/Editing/LineNumberMargin.cs
src/AvaloniaEdit/Rendering/FormattedTextExtensions.cs
src/AvaloniaEdit/Rendering/TextView.cs
src/AvaloniaEdit/Text/TextLineRun.cs
src/AvaloniaEdit/Utils/TextFormatterFactory.cs

Updates to new avalonia apis in 0.5 alpha release.

Update to avalonia 0 5

---

src/AvaloniaEdit/Editing/EditingCommandHandler.cs
src/AvaloniaEdit/Editing/TextArea.cs

This fixes not rendering with single line of text.

invalidate arrange when document is changed.

---

build.cake
src/AvaloniaEdit/AvaloniaEdit.csproj
src/AvaloniaEdit/Document/TextLocation.cs
src/AvaloniaEdit/Editing/AbstractMargin.cs
src/AvaloniaEdit/Editing/EditingCommandHandler.cs
src/AvaloniaEdit/Editing/LineNumberMargin.cs
src/AvaloniaEdit/Editing/TextArea.cs
src/AvaloniaEdit/Folding/FoldingMargin.cs
src/AvaloniaEdit/Highlighting/HighlightingDefinitionTypeConverter.cs
src/AvaloniaEdit/Highlighting/IHighlightingDefinition.cs

- Updates to netstandard1.3 (required for compatibility with latest avalonia builds)
- Fixes lock up when copying and pasting on Linux from external apps.

Netstandard1.3

---

AvaloniaEdit.sln
src/AvaloniaEdit/AvaloniaEdit.csproj
src/AvaloniaEdit/Utils/WeakEventManagerBase.cs
src/build/AvaloniaEdit.props

events that were of PropertyChangedHandlers meaning lots of events were being sent to the wrong instances.

fixes major bug in weak event manager where it would only unsubscribe

---

src/AvaloniaEdit/Document/TextDocument.cs
src/AvaloniaEdit/Highlighting/HighlightingBrush.cs
src/AvaloniaEdit/Rendering/ColumnRulerRenderer.cs
src/AvaloniaEdit/Rendering/CurrentLineHighlightRenderer.cs
src/AvaloniaEdit/Rendering/SingleCharacterElementGenerator.cs
src/AvaloniaEdit/Snippets/SnippetReplaceableTextElement.cs

objects should be able to initialize in the background

Multithreading

---

src/AvaloniaEdit/Highlighting/HighlightingColorizer.cs
src/AvaloniaEdit/Rendering/TextView.cs
src/AvaloniaEdit/Text/TextLineRun.cs
src/AvaloniaEdit/Text/TextRunProperties.cs

Ported support for FontWeight and FontStyle from AvalonEdit WPF

---

src/AvaloniaEdit/Text/TextLineImpl.cs

#48 
Knwon issue: 
- does not work properly when horizontal scrolling is disabled

Fix wrapping bug

---

src/AvaloniaEdit/Rendering/TextView.cs
src/AvaloniaEdit/Rendering/VisualLineLinkText.cs

Implement: hand cursor on a link
Fix: move caret on a link

Implement hand cursor on hyperlink

---

src/AvaloniaEdit/Search/SearchPanel.cs
src/AvaloniaEdit/Search/SearchPanel.xaml

* Fix no match popup
* Fix Bindings
* Fix text input

Fix Search Panel

---

Directory.Build.props

Update Avalonia to v0.8

---

Directory.Build.props
src/AvaloniaEdit.Demo/AvaloniaEdit.Demo.csproj
src/AvaloniaEdit/AvaloniaEdit.csproj
test/AvaloniaEdit.Tests/AvaloniaMocks/MockPlatformRenderInterface.cs
test/AvaloniaEdit.Tests/AvaloniaMocks/MockStreamGeometryImpl.cs
test/AvaloniaEdit.Tests/AvaloniaMocks/UnitTestApplication.cs

Updated Avalonia

---

src/AvaloniaEdit/Rendering/TextView.cs
src/AvaloniaEdit/Text/TextLineRun.cs
src/AvaloniaEdit/Utils/TextFormatterFactory.cs

As described in https://github.com/AvaloniaUI/AvaloniaEdit/issues/108

fix memory leak

---

build.ps1
build.sh
src/AvaloniaEdit.Demo/AvaloniaEdit.Demo.csproj

Change '-' in front of the cake.exe's option to '--'.

---

Directory.Build.props
build.cake
src/AvaloniaEdit/AvaloniaEdit.csproj
src/AvaloniaEdit/Highlighting/HighlightedLine.cs
src/AvaloniaEdit/Highlighting/HtmlClipboard.cs
src/AvaloniaEdit/Highlighting/HtmlRichTextWriter.cs
src/AvaloniaEdit/Utils/RichTextWriter.cs
test/AvaloniaEdit.Tests/AvaloniaEdit.Tests.csproj
test/AvaloniaEdit.Tests/AvaloniaMocks/MockPlatformRenderInterface.cs
test/AvaloniaEdit.Tests/AvaloniaMocks/MockRuntimePlatform.cs
test/AvaloniaEdit.Tests/AvaloniaMocks/MockStreamGeometryImpl.cs
test/AvaloniaEdit.Tests/AvaloniaMocks/MockWindowingPlatform.cs
test/AvaloniaEdit.Tests/AvaloniaMocks/TestServices.cs
test/AvaloniaEdit.Tests/AvaloniaMocks/UnitTestApplication.cs
test/AvaloniaEdit.Tests/Editing/ChangeDocumentTests.cs
test/AvaloniaEdit.Tests/Highlighting/HtmlClipboardTests.cs

This PR enable and updates the NUnit test project, that was out of date:
-  Update to Avalonia 0.10.0
- Update the test project to net5
- Complete the Rich/HTML text writer implementation
- Make nunit tests to pass

Fix & update nunit tests

---

src/AvaloniaEdit.TextMate/TextEditorModel.cs
src/AvaloniaEdit.TextMate/TextMate.cs

This PR adds a new method in `AvaloniaEdit.TextMate.TextMate` class that allows registering an exception handler. 
```
public static void RegisterExceptionHandler(Action<Exception> handler)
{
_exceptionHandler = handler;
}
```
The exception handler is invoked whenever an exception is thrown in any AvaloniaEdit event handler.

Added an exception handler to the TextMate installation

---

.gitignore

Ignore local Visual Studio Code configuration.

Added .vscode to .gitignore 

---

src/AvaloniaEdit/Rendering/SingleCharacterElementGenerator.cs
test/AvaloniaEdit.Tests/Text/TextLineRunTests.cs

Fix tab glyph extra width

---

src/AvaloniaEdit.TextMate/TextEditorModel.cs

Fix syntax highlighting is not applied sometimes

---

src/AvaloniaEdit.TextMate/Attributes.cs
src/AvaloniaEdit.TextMate/TextEditorModel.cs
test/AvaloniaEdit.Tests/TextMate/TextEditorModelTests.cs

Handle document changes that are between:
```chsarp
_textEditor.Document.BeginUpdate();
// stuff
_textEditor.Document.EndUpdate();
```

Handle batch documents updates

---

src/AvaloniaEdit/TextEditor.cs

Fixes #149.
`ScrollTo` functionality was not ported and was still commented. Uncommented and ported.

Enable ScrollTo functionality

---

Directory.Build.props

Include project updates from the upstream project.
- https://github.com/danipen/TextMateSharp/pull/26
- https://github.com/danipen/TextMateSharp/pull/27
* Fixed some bugs.
* Improve multithreading.
* Improve the performance parsing tokens.

Update TextMateSharp to 1.0.40

---

Directory.Build.props
src/AvaloniaEdit.Demo/Resources/SampleFiles/text.bibtex
src/AvaloniaEdit.Demo/Resources/SampleFiles/text.tex
src/AvaloniaEdit.Demo/Resources/SampleFiles/text.tex.latex

This new TextMateSharp version includes:
* Updated all grammar definitions to the latest version.
* LaTeX language support.
* Fixed NRE parsing some token rules.

Update to TextMateSharp 1.0.43

---

src/AvaloniaEdit.Demo/MainWindow.xaml.cs
src/AvaloniaEdit/AvaloniaEdit.xaml
src/AvaloniaEdit/Rendering/VisualLine.cs
src/AvaloniaEdit/Rendering/VisualLineDrawingVisual.xaml

Get the current cursor from the TextView and set it to the VisualLineDrawingVisual when being constructed.

Use IBeam cursor for lines

---

src/AvaloniaEdit/Rendering/TextView.cs

Replace tabs with spaces and apply format.

Reformat TextView.cs

---

src/AvaloniaEdit/Rendering/VisualLine.cs

Reformat code

---

Directory.Build.props

Support apple silicon for TextMateSharp.
More info: https://github.com/danipen/TextMateSharp/pull/35

Use TextMateSharp 1.0.46

---

src/AvaloniaEdit/Rendering/ColumnRulerRenderer.cs
src/AvaloniaEdit/Rendering/TextView.cs
src/AvaloniaEdit/Utils/ExtensionMethods.cs

Minor improvements to the column ruler rendering.
- Snap the column ruler line to device pixels to avoid antialiased (blurry) lines.
- Make the column ruler color a little bit lighter.

Improve colum ruler rendering

---

Directory.Build.props

This new release of TextmateSharp includes:
- Fix cpp grammar: https://github.com/danipen/TextMateSharp/pull/38
- Reduce heap allocs: https://github.com/danipen/TextMateSharp/pull/14

Update TextMateSharp to 1.0.49

---

Directory.Build.props
src/AvaloniaEdit.Demo/Resources/SampleFiles/document.adoc

- Fixes #290 
- Also added sample document for asciidoc

Update text mate sharp to 1.0.50

---

azure-pipelines.yml

Pack AvaloniaEdit with Release configuration

---

src/AvaloniaEdit/Search/SearchPanel.cs

Handle invalid SearchPatternException properly

---

src/AvaloniaEdit/RoutedCommand.cs

Fix RoutedCommand input element tracking

---

src/AvaloniaEdit/Snippets/SnippetReplaceableTextElement.cs

fixes https://github.com/AvaloniaUI/AvaloniaEdit/issues/377

SnippetReplaceableTextElement - geometry null guard

---

src/AvaloniaEdit/Editing/TextArea.cs

bug  https://github.com/AvaloniaUI/AvaloniaEdit/issues/374

Fixes #374 Crash in android

---

src/AvaloniaEdit/Editing/EditingCommandHandler.cs

Fix undo (Ctrl+Z) exception after not successful pasting

---

src/AvaloniaEdit/TextEditor.cs

Use GetBindingObservable instead of `new Binding`

---

src/AvaloniaEdit/CodeCompletion/CompletionList.cs
src/AvaloniaEdit/CodeCompletion/CompletionWindowBase.cs

Fix: #413 CompletionWindow doesn't work with mouse click

---

Directory.Build.props
src/AvaloniaEdit.TextMate/TextMateColoringTransformer.cs
src/AvaloniaEdit.TextMate/TextTransformation.cs

This version updates the csharp grammar to the latest available version (https://github.com/microsoft/vscode/commit/35d97bc7e439fce0f50f42074041ab2d8571b20a)

Update TextMateSharp to 1.0.57

---

src/AvaloniaEdit/CodeCompletion/CompletionList.xaml

Fixes #449 where code completion throws an exception when it opens the popup.

Fixes #449 code completion throws an Exception upon Open

---

src/AvaloniaEdit.Demo/MainWindow.xaml
src/AvaloniaEdit/Editing/TextArea.cs
src/AvaloniaEdit/Editing/TextArea.xaml
src/AvaloniaEdit/TextEditor.cs

Support watermark text when the text in the text area is empty:
https://github.com/user-attachments/assets/4b28fc6b-d577-40e0-9e84-4869c92b6d1a

Add watermark support

---

src/AvaloniaEdit.Demo/AvaloniaEdit.Demo.csproj

* target from not6 to net 8
* change win7-x64 to win-x64 RuntimeIdentifier

Sample project Net + runtime identifier update

---

src/AvaloniaEdit.TextMate/TextMate.cs

Re Open for #487
Sorry for the inconvenience

Feature: Allow loading grammar files from path

---

src/AvaloniaEdit/Editing/EditingCommandHandler.cs

This PR just remove a line added by mistake.

Remove unwanted code

---

src/AvaloniaEdit.Demo/Resources/SampleFiles/text.html.cshtml

Hi There is issue with text.html.cshtml file inside AvaloniaEdit.Demo Project
this pr fixes it

fix syntax error in text.html.cshtml

---

src/AvaloniaEdit/Editing/SelectionMouseHandler.cs

This PR adds a handler for `ScrollOffsetChanged` to the `SelectionMouseHandler`.
Fixes #426.

Fix: Update the selection when scrolling
